content:
 - name: docs
   label: Documentation
   type: collection
   path: src/docs
   fields:
    - {name: title, label: Title, type: string, required: true }
    - { name: body, label: Body,  type: rich-text }

media: files