content:
 - name: docs
   label: Documentation
   type: collection
   path: src/docs
   view:
    fields: [ title, date, publish ] 
   fields:
    - {name: title, label: Title, type: string, required: true }
    - { name: image, label: Image, type: image,  required: true }
    - { name: publish, label: Publish, type: boolean,  required: true }
    - { name: date, label: Date, type: date }
    - { name: body, label: Body,  type: rich-text }
 - name: anime
   label: Anime
   type: collection
   path: src/anime
   view:
    fields: [ title, date, publish ] 
   fields:
    - {name: title, label: Title, type: string, required: true }
    - { name: image, label: Image, type: image }
    - { name: publish, label: Publish, type: boolean }
    - { name: date, label: Date, type: date }
    - { name: body, label: Body,  type: rich-text }
    
  
media: files
